zuul:
  ribbonIsolationStrategy: THREAD
  threadPool:
    useSeparateThreadPools: true
  ignored-service: "*"
  prefix: /api
  routes:
    story-service:
      path: /post/**
      serviceId: review-service
      stripPrefix: false


hystrix:
  command:
    review-service:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 20000

review-service:
  ribbon:
    eureka:
      enabled: true
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    ConnectTimeout: 5000
    ReadTimeout: 5000

    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100



eureka:
  client:
    healthcheck: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://{localhost:8761}}/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      perferIpAddress: true

server:
  port: 4000