server:
  port: 80
spring:
  application:
    name: review-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/REVIEWHUB?allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: {username}
    password: {password}
  jpa:
    database-platform: org.hibernate.dialect.MYSQL5Dialect
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

security:
  oauth2:
    client:
      client-id: {github_client_id}
      client-secret: {github_client_password}
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      client-authentication-scheme: form
    resource:
      user-info-uri: https://api.github.com/user

eureka:
  client:
    healthcheck:
      enabled: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/
  instance:
    prefer-ip-address: true

cors:
  mappings:
    /*:
      allowedOrigins: http://localhost:8080
      allowedHeaders:
        - X-Requested-With
